# Generated by Django 5.2.8 on 2025-11-29 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uk', models.CharField(max_length=200, verbose_name='Назва програми (укр)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Program name (eng)')),
                ('program_type', models.CharField(choices=[('exchange', 'Exchange Program'), ('degree', 'Degree Program'), ('short_term', 'Short-term Program')], default='exchange', max_length=20)),
                ('study_level', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD')], max_length=20)),
                ('faculty_uk', models.CharField(max_length=100, verbose_name='Факультет (укр)')),
                ('faculty_en', models.CharField(blank=True, max_length=100, verbose_name='Faculty (eng)')),
                ('description_uk', models.TextField(blank=True, default='', verbose_name='Опис (укр)')),
                ('description_en', models.TextField(blank=True, default='', verbose_name='Description (eng)')),
                ('testimonial_uk', models.TextField(blank=True, default='', verbose_name='Відгук (укр)')),
                ('testimonial_en', models.TextField(blank=True, default='', verbose_name='Testimonial (eng)')),
                ('useful_link_1', models.URLField(blank=True, null=True, verbose_name='Корисне посилання 1')),
                ('useful_link_2', models.URLField(blank=True, null=True, verbose_name='Корисне посилання 2')),
                ('useful_link_3', models.URLField(blank=True, null=True, verbose_name='Корисне посилання 3')),
                ('useful_link_1_title_uk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва посилання 1 (укр)')),
                ('useful_link_2_title_uk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва посилання 2 (укр)')),
                ('useful_link_3_title_uk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва посилання 3 (укр)')),
                ('useful_link_1_title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва посилання 1 (eng)')),
                ('useful_link_2_title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва посилання 2 (eng)')),
                ('useful_link_3_title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва посилання 3 (eng)')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by_name', models.CharField(blank=True, default='', max_length=100)),
                ('submitted_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('home_university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_programs', to='universities.university', verbose_name='Університет відправлення')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_programs', to='universities.university', verbose_name='Університет прийому')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
