# Generated by Django 4.2 on 2025-08-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='program',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='program',
            name='home_university',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='program',
            name='study_level',
            field=models.CharField(blank=True, choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD')], max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='testimonial',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('exchange', 'Exchange Program'), ('degree', 'Degree Program'), ('short_term', 'Short-term Program'), ('erasmus', 'Erasmus+'), ('academic_mobility', 'Academic Mobility')], max_length=20),
        ),
    ]
