# Generated by Django 5.2.8 on 2025-12-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='user_university_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Вказаний користувачем університет'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name_uk',
            field=models.CharField(blank=True, max_length=200, verbose_name='Назва програми (укр)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='submitted_by_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email заявника'),
        ),
        migrations.AlterField(
            model_name='program',
            name='submitted_by_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name="Ім'я заявника"),
        ),
    ]
