# Generated by Django 5.2.8 on 2025-12-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_program_user_university_text_alter_program_name_uk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='name_uk',
            field=models.CharField(max_length=200, verbose_name='Назва програми (укр)'),
        ),
    ]
