# Generated by Django 5.2.8 on 2025-12-03 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_program_name_uk'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='home_university_details',
            field=models.TextField(blank=True, verbose_name='Деталі домашнього університету'),
        ),
        migrations.AddField(
            model_name='program',
            name='home_university_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Університет відправлення (Текст)'),
        ),
        migrations.AddField(
            model_name='program',
            name='university_details',
            field=models.TextField(blank=True, verbose_name='Деталі приймаючого університету'),
        ),
        migrations.AddField(
            model_name='program',
            name='university_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Університет прийому (Текст)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description_uk',
            field=models.TextField(blank=True, default='', verbose_name='Опис/Відгук'),
        ),
        migrations.AlterField(
            model_name='program',
            name='faculty_uk',
            field=models.CharField(max_length=100, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='program',
            name='home_university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_programs', to='universities.university', verbose_name='Університет відправлення (ID)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name_uk',
            field=models.CharField(max_length=200, verbose_name='Назва програми'),
        ),
        migrations.AlterField(
            model_name='program',
            name='study_level',
            field=models.CharField(max_length=50, verbose_name='Рівень навчання'),
        ),
        migrations.AlterField(
            model_name='program',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_programs', to='universities.university', verbose_name='Університет прийому (ID)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='user_university_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Вказаний користувачем університет (старе поле)'),
        ),
    ]
