# Generated by Django 4.2 on 2025-08-14 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_program_benefits_alter_program_contact_email_and_more'),
    ]

    operations = [
    ]
