# Generated by Django 5.2.8 on 2025-12-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_program_home_university_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description_uk',
            field=models.TextField(blank=True, default='', verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='program',
            name='home_university_details',
            field=models.TextField(blank=True, verbose_name='Інформація про дом. університет від користувача'),
        ),
        migrations.AlterField(
            model_name='program',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Опубліковано'),
        ),
        migrations.AlterField(
            model_name='program',
            name='university_details',
            field=models.TextField(blank=True, verbose_name='Інформація про університет від користувача'),
        ),
    ]
