# Generated by Django 4.2 on 2025-08-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20250815_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='application_deadline',
        ),
        migrations.RemoveField(
            model_name='program',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='program',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='program',
            name='country',
        ),
        migrations.RemoveField(
            model_name='program',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='program',
            name='language',
        ),
        migrations.RemoveField(
            model_name='program',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='program',
            name='website',
        ),
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('exchange', 'Exchange Program'), ('degree', 'Degree Program'), ('short_term', 'Short-term Program')], default='exchange', max_length=20),
        ),
        migrations.AlterField(
            model_name='program',
            name='study_level',
            field=models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD')], max_length=20),
        ),
    ]
