# Generated by Django 4.2 on 2025-08-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_remove_program_application_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='faculty',
            field=models.CharField(choices=[('arts', 'Arts and Humanities'), ('business', 'Business and Economics'), ('engineering', 'Engineering and Technology'), ('law', 'Law'), ('medicine', 'Medicine and Health'), ('science', 'Natural Sciences'), ('social', 'Social Sciences'), ('computer', 'Computer Science'), ('education', 'Education'), ('other', 'Other')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
