# Generated by Django 5.2.8 on 2025-12-03 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_alter_program_description_uk_and_more'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description_uk',
            field=models.TextField(blank=True, default='', verbose_name='Опис/Відгук'),
        ),
        migrations.AlterField(
            model_name='program',
            name='home_university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_programs', to='universities.university', verbose_name='Університет відправлення (з бази)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='home_university_details',
            field=models.TextField(blank=True, verbose_name='Інформація про дом. університет / Нова назва'),
        ),
        migrations.AlterField(
            model_name='program',
            name='home_university_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Дом. Університет (Текст - Legacy)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_programs', to='universities.university', verbose_name='Університет прийому (з бази)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='university_details',
            field=models.TextField(blank=True, verbose_name='Інформація про університет / Нова назва'),
        ),
        migrations.AlterField(
            model_name='program',
            name='university_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Університет (Текст - Legacy)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='user_university_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
