# Generated by Django 5.2.8 on 2025-12-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_alter_program_description_uk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='home_university_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Legacy Text'),
        ),
        migrations.AlterField(
            model_name='program',
            name='university_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Legacy Text'),
        ),
    ]
