# Generated by Django 4.2 on 2025-08-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_program_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='faculty',
            field=models.CharField(max_length=100),
        ),
    ]
