# Generated by Django 4.2 on 2025-09-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_alter_program_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='useful_link_1',
            field=models.URLField(blank=True, null=True, verbose_name='Корисне посилання 1'),
        ),
        migrations.AddField(
            model_name='program',
            name='useful_link_1_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва посилання 1'),
        ),
        migrations.AddField(
            model_name='program',
            name='useful_link_2',
            field=models.URLField(blank=True, null=True, verbose_name='Корисне посилання 2'),
        ),
        migrations.AddField(
            model_name='program',
            name='useful_link_2_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва посилання 2'),
        ),
        migrations.AddField(
            model_name='program',
            name='useful_link_3',
            field=models.URLField(blank=True, null=True, verbose_name='Корисне посилання 3'),
        ),
        migrations.AddField(
            model_name='program',
            name='useful_link_3_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва посилання 3'),
        ),
    ]
