# Generated by Django 5.2.8 on 2025-12-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_alter_program_home_university_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='study_level',
            field=models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD'), ('Other', 'Other')], max_length=50, verbose_name='Рівень навчання'),
        ),
    ]
