# Generated by Django 5.2.8 on 2025-12-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_alter_program_study_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description_uk',
            field=models.TextField(blank=True, default='', verbose_name='Опис (укр)'),
        ),
    ]
