# Generated by Django 4.2 on 2025-10-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_program_useful_link_1_program_useful_link_1_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='description',
        ),
        migrations.RemoveField(
            model_name='program',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='program',
            name='home_university',
        ),
        migrations.RemoveField(
            model_name='program',
            name='name',
        ),
        migrations.RemoveField(
            model_name='program',
            name='testimonial',
        ),
        migrations.RemoveField(
            model_name='program',
            name='useful_link_1_title',
        ),
        migrations.RemoveField(
            model_name='program',
            name='useful_link_2_title',
        ),
        migrations.RemoveField(
            model_name='program',
            name='useful_link_3_title',
        ),
        migrations.AddField(
            model_name='program',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Description (eng)'),
        ),
        migrations.AddField(
            model_name='program',
            name='description_uk',
            field=models.TextField(blank=True, default='', verbose_name='Опис (укр)'),
        ),
        migrations.AddField(
            model_name='program',
            name='faculty_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Faculty (eng)'),
        ),
        migrations.AddField(
            model_name='program',
            name='faculty_uk',
            field=models.CharField(default=1, max_length=100, verbose_name='Факультет (укр)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='home_university_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Home university (eng)'),
        ),
        migrations.AddField(
            model_name='program',
            name='home_university_uk',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Домашній університет (укр)'),
        ),
        migrations.AddField(
            model_name='program',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Program name (eng)'),
        ),
        migrations.AddField(
            model_name='program',
            name='name_uk',
            field=models.CharField(default=1, max_length=200, verbose_name='Назва програми (укр)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='testimonial_en',
            field=models.TextField(blank=True, default='', verbose_name='Testimonial (eng)'),
        ),
        migrations.AddField(
            model_name='program',
            name='testimonial_uk',
            field=models.TextField(blank=True, default='', verbose_name='Відгук (укр)'),
        ),
        migrations.AddField(
            model_name='program',
            name='useful_link_1_title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва посилання 1 (eng)'),
        ),
        migrations.AddField(
            model_name='program',
            name='useful_link_1_title_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва посилання 1 (укр)'),
        ),
        migrations.AddField(
            model_name='program',
            name='useful_link_2_title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва посилання 2 (eng)'),
        ),
        migrations.AddField(
            model_name='program',
            name='useful_link_2_title_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва посилання 2 (укр)'),
        ),
        migrations.AddField(
            model_name='program',
            name='useful_link_3_title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва посилання 3 (eng)'),
        ),
        migrations.AddField(
            model_name='program',
            name='useful_link_3_title_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва посилання 3 (укр)'),
        ),
    ]
