# Generated by Django 4.2 on 2025-10-25 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_alter_university_options_and_more'),
        ('programs', '0009_remove_program_description_remove_program_faculty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='home_university_en',
        ),
        migrations.RemoveField(
            model_name='program',
            name='home_university_uk',
        ),
        migrations.AddField(
            model_name='program',
            name='home_university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_programs', to='universities.university', verbose_name='Університет відправлення'),
        ),
        migrations.AlterField(
            model_name='program',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_programs', to='universities.university', verbose_name='Університет прийому'),
        ),
    ]
