# Generated by Django 4.2.27 on 2026-02-01 22:38

from django.db import migrations, models
from django.utils.text import slugify


def populate_program_slugs(apps, schema_editor):
    """Populate slugs for existing programs"""
    Program = apps.get_model('programs', 'Program')
    for program in Program.objects.all():
        if not program.slug:
            base_name = program.name_en if program.name_en else program.name_uk
            base_slug = slugify(base_name, allow_unicode=True)
            
            if not base_slug:
                base_slug = f'program-{program.pk}'
            
            unique_slug = base_slug
            counter = 1
            while Program.objects.filter(slug=unique_slug).exclude(pk=program.pk).exists():
                unique_slug = f"{base_slug}-{counter}"
                counter += 1
            
            program.slug = unique_slug
            program.save(update_fields=['slug'])


def reverse_populate(apps, schema_editor):
    """Reverse migration"""
    pass


class Migration(migrations.Migration):
    atomic = False  # Disable atomic to allow step-by-step operations

    dependencies = [
        ('programs', '0009_alter_program_description_uk'),
    ]

    operations = [
        # Step 1: Add slug as CharField (no automatic db_index)
        migrations.AddField(
            model_name='program',
            name='slug',
            field=models.CharField(blank=True, max_length=255, default='', verbose_name='URL Slug'),
            preserve_default=False,
        ),
        # Step 2: Populate slugs for existing records
        migrations.RunPython(populate_program_slugs, reverse_populate),
        # Step 3: Convert to SlugField with unique constraint
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(
                blank=True,
                help_text='Автоматично генерується з назви',
                max_length=255,
                unique=True,
                verbose_name='URL Slug'
            ),
        ),
    ]
