# Generated by Django 5.2.8 on 2025-11-29 16:36

import django.core.validators
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uk', models.CharField(max_length=200, verbose_name='Назва університету (укр)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='University name (eng)')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Країна')),
                ('location_uk', models.CharField(blank=True, default='', max_length=200, verbose_name='Місто/Адреса (укр)')),
                ('location_en', models.CharField(blank=True, default='', max_length=200, verbose_name='Location/Address (eng)')),
                ('description_uk', models.TextField(blank=True, verbose_name='Опис (укр)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (eng)')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Контактний email')),
                ('website_url', models.URLField(verbose_name='Вебсайт')),
                ('additional_info_uk', models.TextField(blank=True, verbose_name='Додаткова інформація (укр)')),
                ('additional_info_en', models.TextField(blank=True, verbose_name='Additional info (eng)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])], verbose_name='Логотип')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='university_backgrounds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Фонове зображення')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Університет',
                'verbose_name_plural': 'Університети',
                'ordering': ['name_uk'],
            },
        ),
    ]
