# Generated by Django 4.2.27 on 2026-02-01 22:38

from django.db import migrations, models
from django.utils.text import slugify


def populate_university_slugs(apps, schema_editor):
    """Populate slugs for existing universities"""
    University = apps.get_model('universities', 'University')
    for uni in University.objects.all():
        if not uni.slug:
            base_name = uni.name_en if uni.name_en else uni.name_uk
            base_slug = slugify(base_name, allow_unicode=True)
            
            if not base_slug:
                base_slug = f'university-{uni.pk}'
            
            unique_slug = base_slug
            counter = 1
            while University.objects.filter(slug=unique_slug).exclude(pk=uni.pk).exists():
                unique_slug = f"{base_slug}-{counter}"
                counter += 1
            
            uni.slug = unique_slug
            uni.save(update_fields=['slug'])


def reverse_populate(apps, schema_editor):
    """Reverse migration"""
    pass


class Migration(migrations.Migration):
    atomic = False  # Disable atomic to allow step-by-step operations

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        # Step 1: Add slug as CharField (no automatic db_index)
        migrations.AddField(
            model_name='university',
            name='slug',
            field=models.CharField(blank=True, max_length=255, default='', verbose_name='URL Slug'),
            preserve_default=False,
        ),
        # Step 2: Populate slugs for existing records
        migrations.RunPython(populate_university_slugs, reverse_populate),
        # Step 3: Convert to SlugField with unique constraint
        migrations.AlterField(
            model_name='university',
            name='slug',
            field=models.SlugField(
                blank=True,
                help_text='Автоматично генерується з назви',
                max_length=255,
                unique=True,
                verbose_name='URL Slug'
            ),
        ),
    ]
