# Generated by Django 4.2 on 2025-08-03 20:24

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_add_location_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['name'], 'verbose_name': 'Університет', 'verbose_name_plural': 'Університети'},
        ),
        migrations.AlterField(
            model_name='university',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Додаткова інформація (для Read More)'),
        ),
        migrations.AlterField(
            model_name='university',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='university_backgrounds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Фонове зображення (для Read More)'),
        ),
        migrations.AlterField(
            model_name='university',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Контактний email'),
        ),
        migrations.AlterField(
            model_name='university',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='university',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Опубліковано'),
        ),
        migrations.AlterField(
            model_name='university',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Місто/Адреса'),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='university_logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])], verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Назва університету'),
        ),
        migrations.AlterField(
            model_name='university',
            name='website_url',
            field=models.URLField(verbose_name='Вебсайт'),
        ),
    ]
