# Generated by Django 4.2 on 2025-10-25 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_alter_university_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['name_uk'], 'verbose_name': 'Університет', 'verbose_name_plural': 'Університети'},
        ),
        migrations.RemoveField(
            model_name='university',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='university',
            name='description',
        ),
        migrations.RemoveField(
            model_name='university',
            name='location',
        ),
        migrations.RemoveField(
            model_name='university',
            name='name',
        ),
        migrations.AddField(
            model_name='university',
            name='additional_info_en',
            field=models.TextField(blank=True, verbose_name='Additional info (eng)'),
        ),
        migrations.AddField(
            model_name='university',
            name='additional_info_uk',
            field=models.TextField(blank=True, verbose_name='Додаткова інформація (укр)'),
        ),
        migrations.AddField(
            model_name='university',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (eng)'),
        ),
        migrations.AddField(
            model_name='university',
            name='description_uk',
            field=models.TextField(blank=True, verbose_name='Опис (укр)'),
        ),
        migrations.AddField(
            model_name='university',
            name='location_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Location/Address (eng)'),
        ),
        migrations.AddField(
            model_name='university',
            name='location_uk',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Місто/Адреса (укр)'),
        ),
        migrations.AddField(
            model_name='university',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='University name (eng)'),
        ),
        migrations.AddField(
            model_name='university',
            name='name_uk',
            field=models.CharField(default=1, max_length=200, verbose_name='Назва університету (укр)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='university',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='university_backgrounds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Фонове зображення'),
        ),
    ]
