# Generated by Django 4.2 on 2025-08-19 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_ua', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.CharField(max_length=255)),
                ('question_ua', models.CharField(max_length=255)),
                ('answer_en', models.TextField()),
                ('answer_ua', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('author_ua', models.CharField(max_length=100)),
                ('editor', models.CharField(max_length=100)),
                ('editor_ua', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(to='faq_app.faqcategory')),
            ],
        ),
    ]
