# Generated by Django 4.2 on 2025-10-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqcategory',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Category name (English)'),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='name_ua',
            field=models.CharField(max_length=100, verbose_name='Назва категорії (Українська)'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='answer_en',
            field=models.TextField(verbose_name='Answer (English)'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='answer_ua',
            field=models.TextField(verbose_name='Відповідь (Українська)'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Author (English)'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='author_ua',
            field=models.CharField(max_length=100, verbose_name='Автор (Українська)'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='editor',
            field=models.CharField(max_length=100, verbose_name='Editor (English)'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='editor_ua',
            field=models.CharField(max_length=100, verbose_name='Редактор (Українська)'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='question_en',
            field=models.CharField(max_length=255, verbose_name='Question (English)'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='question_ua',
            field=models.CharField(max_length=255, verbose_name='Питання (Українська)'),
        ),
    ]
