# Generated by Django 4.2 on 2025-10-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0002_alter_faqcategory_name_en_alter_faqcategory_name_ua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqitem',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубліковано'),
        ),
    ]
