# Generated by Django 5.2.8 on 2025-11-29 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Category name (English)')),
                ('name_ua', models.CharField(max_length=100, verbose_name='Назва категорії (Українська)')),
            ],
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.CharField(max_length=255, verbose_name='Question (English)')),
                ('question_ua', models.CharField(max_length=255, verbose_name='Питання (Українська)')),
                ('answer_en', models.TextField(verbose_name='Answer (English)')),
                ('answer_ua', models.TextField(verbose_name='Відповідь (Українська)')),
                ('author', models.CharField(max_length=100, verbose_name='Author (English)')),
                ('author_ua', models.CharField(max_length=100, verbose_name='Автор (Українська)')),
                ('editor', models.CharField(max_length=100, verbose_name='Editor (English)')),
                ('editor_ua', models.CharField(max_length=100, verbose_name='Редактор (Українська)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(to='faq.faqcategory')),
            ],
        ),
    ]
